import type { Vehicle } from "@/types/domain";

const now = Date.now();
const day = 86_400_000;

export const demoVehicles: Vehicle[] = [
  {
    id: "demo-toyota-rav4",
    ownerId: "demo",
    year: 2022,
    itemType: "SUV",
    brand: "Toyota",
    model: "RAV4 XLE",
    engine: "2.5L I4",
    transmission: "Automática",
    fuelType: "Gasolina",
    drivetrain: "AWD",
    cylinders: 4,
    damageLevel: "GREEN",
    images: Array.from({ length: 5 }, (_, index) => ({
      id: `rav4-${index}`,
      url: `https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1400&q=80&sig=${index}`,
      storagePath: "demo",
      order: index,
    })),
    basePrice: 98000,
    currentBid: 104500,
    startAt: new Date(now - day).toISOString(),
    endAt: new Date(now + day * 2).toISOString(),
    createdAt: new Date(now - day * 3).toISOString(),
    updatedAt: new Date(now).toISOString(),
  },
  {
    id: "demo-ford-ranger",
    ownerId: "demo",
    year: 2020,
    itemType: "Pickup",
    brand: "Ford",
    model: "Ranger XLT",
    engine: "2.3L EcoBoost",
    transmission: "Automática",
    fuelType: "Gasolina",
    drivetrain: "4WD",
    cylinders: 4,
    damageLevel: "YELLOW",
    images: Array.from({ length: 5 }, (_, index) => ({
      id: `ranger-${index}`,
      url: `https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=1400&q=80&sig=${index}`,
      storagePath: "demo",
      order: index,
    })),
    basePrice: 72000,
    startAt: new Date(now + day).toISOString(),
    endAt: new Date(now + day * 4).toISOString(),
    createdAt: new Date(now - day).toISOString(),
    updatedAt: new Date(now).toISOString(),
  },
  {
    id: "demo-honda-civic",
    ownerId: "demo",
    year: 2019,
    itemType: "Sedán",
    brand: "Honda",
    model: "Civic EX",
    engine: "1.5L Turbo",
    transmission: "CVT",
    fuelType: "Gasolina",
    drivetrain: "FWD",
    cylinders: 4,
    damageLevel: "RED",
    images: Array.from({ length: 5 }, (_, index) => ({
      id: `civic-${index}`,
      url: `https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1400&q=80&sig=${index}`,
      storagePath: "demo",
      order: index,
    })),
    basePrice: 38500,
    startAt: new Date(now - day * 5).toISOString(),
    endAt: new Date(now - day).toISOString(),
    createdAt: new Date(now - day * 6).toISOString(),
    updatedAt: new Date(now - day).toISOString(),
  },
];
